/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;
import EstructurasDeDatos.ListaVideojuegos.Nodo;
import controller.InformacionVideojuegoController;
/**
 *
 * @author CARLO
 */
public class frmInformacionVideojuego extends javax.swing.JInternalFrame {
private final InformacionVideojuegoController controlador = new InformacionVideojuegoController(this);
Nodo datos;
    /**
     * Creates new form frmInformacionVideojuego
     */
    public frmInformacionVideojuego(Nodo NodoVideojuego) {
        initComponents();
        datos = NodoVideojuego;
        controlador.rellenarDatos(datos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Toolbar = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        Panel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jlbGenero = new javax.swing.JLabel();
        jlbNombre = new javax.swing.JLabel();
        jlbPrecio = new javax.swing.JLabel();
        jlbFecha = new javax.swing.JLabel();
        jlbClasificacion = new javax.swing.JLabel();
        jlbStock = new javax.swing.JLabel();
        jlbPlataforma = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(241, 236, 224));

        Toolbar.setBackground(new java.awt.Color(35, 57, 91));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoGris.png"))); // NOI18N

        javax.swing.GroupLayout ToolbarLayout = new javax.swing.GroupLayout(Toolbar);
        Toolbar.setLayout(ToolbarLayout);
        ToolbarLayout.setHorizontalGroup(
            ToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ToolbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ToolbarLayout.setVerticalGroup(
            ToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ToolbarLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnEliminar.setBackground(new java.awt.Color(200, 157, 60));
        btnEliminar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(241, 236, 224));
        btnEliminar.setText("REGRESAR");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnModificar.setBackground(new java.awt.Color(35, 57, 91));
        btnModificar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(241, 236, 224));
        btnModificar.setText("COMPRAR");
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        Panel2.setBackground(new java.awt.Color(249, 246, 241));

        jLabel10.setBackground(new java.awt.Color(35, 57, 91));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(77, 100, 141));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("NOMBRE:");

        jLabel11.setBackground(new java.awt.Color(35, 57, 91));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(77, 100, 141));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("PRECIO:");

        jLabel12.setBackground(new java.awt.Color(35, 57, 91));
        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(77, 100, 141));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("GÉNERO:");

        jLabel13.setBackground(new java.awt.Color(35, 57, 91));
        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(77, 100, 141));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("CLASIFICACIÓN:");

        jLabel14.setBackground(new java.awt.Color(35, 57, 91));
        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(77, 100, 141));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("PLATAFORMA:");

        jLabel15.setBackground(new java.awt.Color(35, 57, 91));
        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(77, 100, 141));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("FECHA LANZAMIENTO:");

        jLabel16.setBackground(new java.awt.Color(35, 57, 91));
        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(77, 100, 141));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("STOCK DISPONIBLE:");

        jlbGenero.setBackground(new java.awt.Color(35, 57, 91));
        jlbGenero.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jlbGenero.setForeground(new java.awt.Color(77, 100, 141));
        jlbGenero.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbGenero.setText("NOMBRE:");

        jlbNombre.setBackground(new java.awt.Color(35, 57, 91));
        jlbNombre.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jlbNombre.setForeground(new java.awt.Color(77, 100, 141));
        jlbNombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbNombre.setText("NOMBRE:");

        jlbPrecio.setBackground(new java.awt.Color(35, 57, 91));
        jlbPrecio.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jlbPrecio.setForeground(new java.awt.Color(77, 100, 141));
        jlbPrecio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbPrecio.setText("NOMBRE:");

        jlbFecha.setBackground(new java.awt.Color(35, 57, 91));
        jlbFecha.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jlbFecha.setForeground(new java.awt.Color(77, 100, 141));
        jlbFecha.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbFecha.setText("NOMBRE:");

        jlbClasificacion.setBackground(new java.awt.Color(35, 57, 91));
        jlbClasificacion.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jlbClasificacion.setForeground(new java.awt.Color(77, 100, 141));
        jlbClasificacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbClasificacion.setText("NOMBRE:");

        jlbStock.setBackground(new java.awt.Color(35, 57, 91));
        jlbStock.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jlbStock.setForeground(new java.awt.Color(77, 100, 141));
        jlbStock.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbStock.setText("NOMBRE:");

        jlbPlataforma.setBackground(new java.awt.Color(35, 57, 91));
        jlbPlataforma.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jlbPlataforma.setForeground(new java.awt.Color(77, 100, 141));
        jlbPlataforma.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbPlataforma.setText("NOMBRE:");

        javax.swing.GroupLayout Panel2Layout = new javax.swing.GroupLayout(Panel2);
        Panel2.setLayout(Panel2Layout);
        Panel2Layout.setHorizontalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbGenero, javax.swing.GroupLayout.DEFAULT_SIZE, 1178, Short.MAX_VALUE)
                            .addComponent(jlbFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 1178, Short.MAX_VALUE)
                            .addComponent(jlbStock, javax.swing.GroupLayout.DEFAULT_SIZE, 1178, Short.MAX_VALUE)
                            .addComponent(jlbPlataforma, javax.swing.GroupLayout.DEFAULT_SIZE, 1178, Short.MAX_VALUE)
                            .addComponent(jlbClasificacion, javax.swing.GroupLayout.DEFAULT_SIZE, 1178, Short.MAX_VALUE)))
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 1177, Short.MAX_VALUE)
                            .addComponent(jlbPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 1177, Short.MAX_VALUE))))
                .addContainerGap())
        );
        Panel2Layout.setVerticalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jlbNombre))
                .addGap(29, 29, 29)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jlbPrecio))
                .addGap(27, 27, 27)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jlbClasificacion))
                .addGap(31, 31, 31)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jlbGenero))
                .addGap(34, 34, 34)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jlbFecha))
                .addGap(35, 35, 35)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jlbPlataforma))
                .addGap(32, 32, 32)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jlbStock))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(Panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(Panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        this.dispose();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
       
        controlador.comprar(datos);

    }//GEN-LAST:event_btnModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel2;
    private javax.swing.JPanel Toolbar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JLabel jlbClasificacion;
    public javax.swing.JLabel jlbFecha;
    public javax.swing.JLabel jlbGenero;
    public javax.swing.JLabel jlbNombre;
    public javax.swing.JLabel jlbPlataforma;
    public javax.swing.JLabel jlbPrecio;
    public javax.swing.JLabel jlbStock;
    private javax.swing.JLabel lblLogo;
    // End of variables declaration//GEN-END:variables
}
