/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;
import controller.MetodoPagoController;
import model.Producto;
/**
 *
 * @author CARLO
 */
public class frmMetodoDePago extends javax.swing.JInternalFrame {
    private final MetodoPagoController controlador;
    private Producto productoAComprar;
    /**
     * Creates new form frmMetodoDePago
     */
    public frmMetodoDePago(Producto producto) {
        initComponents();
        this.productoAComprar = producto;
        this.controlador = new MetodoPagoController(this);
        buttonSi.setSelected(true);
        buttonSiActionPerformed(null);
        
        buttonNo.addActionListener(this::buttonNoActionPerformed);
        controlador.inicializarCampos();
    }
    
    public Producto getProductoAComprar() {
        return productoAComprar;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Toolbar = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnPagar = new javax.swing.JButton();
        Panel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jlbReferencia = new javax.swing.JLabel();
        jlbTitular = new javax.swing.JLabel();
        jlbDetalles = new javax.swing.JLabel();
        jtfTitular = new javax.swing.JTextField();
        jtfReferencia = new javax.swing.JTextField();
        jtfDetalles = new javax.swing.JTextField();
        buttonSi = new javax.swing.JRadioButton();
        buttonNo = new javax.swing.JRadioButton();
        jlbOtroMetodo = new javax.swing.JLabel();
        jtfNuevoMetodo = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(241, 236, 224));

        Toolbar.setBackground(new java.awt.Color(35, 57, 91));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoGris.png"))); // NOI18N

        javax.swing.GroupLayout ToolbarLayout = new javax.swing.GroupLayout(Toolbar);
        Toolbar.setLayout(ToolbarLayout);
        ToolbarLayout.setHorizontalGroup(
            ToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ToolbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ToolbarLayout.setVerticalGroup(
            ToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ToolbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jLabel8.setBackground(new java.awt.Color(35, 57, 91));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(35, 57, 91));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("METODO DE PAGO");

        btnEliminar.setBackground(new java.awt.Color(200, 157, 60));
        btnEliminar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(241, 236, 224));
        btnEliminar.setText("REGRESAR");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnPagar.setBackground(new java.awt.Color(35, 57, 91));
        btnPagar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnPagar.setForeground(new java.awt.Color(241, 236, 224));
        btnPagar.setText("ACEPTAR");
        btnPagar.addActionListener(this::btnPagarActionPerformed);

        Panel2.setBackground(new java.awt.Color(249, 246, 241));

        jLabel10.setBackground(new java.awt.Color(35, 57, 91));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(77, 100, 141));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("USAR METODO ACTUAL:");

        jlbReferencia.setBackground(new java.awt.Color(35, 57, 91));
        jlbReferencia.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jlbReferencia.setForeground(new java.awt.Color(77, 100, 141));
        jlbReferencia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbReferencia.setText("REFERENCIA:");

        jlbTitular.setBackground(new java.awt.Color(35, 57, 91));
        jlbTitular.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jlbTitular.setForeground(new java.awt.Color(77, 100, 141));
        jlbTitular.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbTitular.setText("TITULAR:");

        jlbDetalles.setBackground(new java.awt.Color(35, 57, 91));
        jlbDetalles.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jlbDetalles.setForeground(new java.awt.Color(77, 100, 141));
        jlbDetalles.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbDetalles.setText("DETALLES:");

        jtfTitular.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jtfTitular.setForeground(new java.awt.Color(35, 57, 91));

        jtfReferencia.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jtfReferencia.setForeground(new java.awt.Color(35, 57, 91));

        jtfDetalles.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jtfDetalles.setForeground(new java.awt.Color(35, 57, 91));

        buttonGroup1.add(buttonSi);
        buttonSi.setForeground(new java.awt.Color(0, 0, 0));
        buttonSi.setSelected(true);
        buttonSi.setText("Si");
        buttonSi.addActionListener(this::buttonSiActionPerformed);

        buttonGroup1.add(buttonNo);
        buttonNo.setForeground(new java.awt.Color(0, 0, 0));
        buttonNo.setText("No");
        buttonNo.addActionListener(this::buttonNoActionPerformed);

        jlbOtroMetodo.setBackground(new java.awt.Color(35, 57, 91));
        jlbOtroMetodo.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jlbOtroMetodo.setForeground(new java.awt.Color(77, 100, 141));
        jlbOtroMetodo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbOtroMetodo.setText("OTRO METODO: ");

        jtfNuevoMetodo.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jtfNuevoMetodo.setForeground(new java.awt.Color(35, 57, 91));

        javax.swing.GroupLayout Panel2Layout = new javax.swing.GroupLayout(Panel2);
        Panel2.setLayout(Panel2Layout);
        Panel2Layout.setHorizontalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addComponent(jtfDetalles, javax.swing.GroupLayout.DEFAULT_SIZE, 1167, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfTitular, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
                            .addComponent(jtfReferencia))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(Panel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addComponent(buttonSi)
                        .addGap(97, 97, 97)
                        .addComponent(jlbOtroMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfNuevoMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttonNo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel2Layout.setVerticalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jlbOtroMetodo)
                    .addComponent(jtfNuevoMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSi))
                .addGap(32, 32, 32)
                .addComponent(buttonNo)
                .addGap(91, 91, 91)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbTitular))
                .addGap(25, 25, 25)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbReferencia)
                    .addComponent(jtfReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbDetalles)
                    .addComponent(jtfDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(168, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(Panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(595, 595, 595)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        this.dispose();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        controlador.finalizarCompra();
    }//GEN-LAST:event_btnPagarActionPerformed

    private void buttonSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSiActionPerformed
        // TODO add your handling code here:
        jlbOtroMetodo.setVisible(false);
        jtfNuevoMetodo.setVisible(false);
        jlbTitular.setVisible(false);
        jtfTitular.setVisible(false);
        jlbReferencia.setVisible(false);
        jtfReferencia.setVisible(false);
        jlbDetalles.setVisible(false);
        jtfDetalles.setVisible(false);
    }//GEN-LAST:event_buttonSiActionPerformed

    private void buttonNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNoActionPerformed
        // TODO add your handling code here:
        jlbOtroMetodo.setVisible(true);
        jtfNuevoMetodo.setVisible(true);
        jlbTitular.setVisible(true);
        jtfTitular.setVisible(true);
        jlbReferencia.setVisible(true);
        jtfReferencia.setVisible(true);
        jlbDetalles.setVisible(true);
        jtfDetalles.setVisible(true);
    }//GEN-LAST:event_buttonNoActionPerformed
    
    public boolean usarMetodoActual() {
        return buttonSi.isSelected();
    }

    public String getTxtNuevoMetodo() {
        return jtfNuevoMetodo.getText().trim();
    }

    public String getTxtTitular() {
        return jtfTitular.getText().trim();
    }

    public String getTxtReferencia() {
        return jtfReferencia.getText().trim();
    }

    public String getTxtDetalles() {
        return jtfDetalles.getText().trim();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel2;
    private javax.swing.JPanel Toolbar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnPagar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton buttonNo;
    private javax.swing.JRadioButton buttonSi;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlbDetalles;
    private javax.swing.JLabel jlbOtroMetodo;
    private javax.swing.JLabel jlbReferencia;
    private javax.swing.JLabel jlbTitular;
    private javax.swing.JTextField jtfDetalles;
    private javax.swing.JTextField jtfNuevoMetodo;
    private javax.swing.JTextField jtfReferencia;
    private javax.swing.JTextField jtfTitular;
    private javax.swing.JLabel lblLogo;
    // End of variables declaration//GEN-END:variables
}
