/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import model.Videojuego;

/**
 *
 * @author shari
 */
public class frmNuevoVideojuego extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmNuevoVideojuego.class.getName());
    /**
     * Creates new form frmNuevaConsola
     */
    public frmNuevoVideojuego() {
        initComponents();
        this.setExtendedState(frmPrincipalAdmin.MAXIMIZED_BOTH);
        
        
        ImageIcon icono = new ImageIcon(
                getClass().getResource("/imagenes/usuario.png")
        );

        Image img = icono.getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH);
        btnUsuario.setIcon(new ImageIcon(img));

        ImageIcon logo = new ImageIcon(getClass().getResource("/imagenes/logoGris.png"));
        Image imagenEscalada = logo.getImage().getScaledInstance(lblLogo.getWidth(), lblLogo.getHeight(), Image.SCALE_SMOOTH);
        lblLogo.setIcon(new ImageIcon(imagenEscalada));
        
        
        jtfPrecio.setOpaque(true);
        jtfPrecio.setBackground(Color.WHITE);
        
         jtfPrecio.setOpaque(true);
        jtfPrecio.setBackground(Color.WHITE);
        
         jtfFechaLanzamiento.setOpaque(true);
        jtfFechaLanzamiento.setBackground(Color.WHITE);
        
         jtfFechaLanzamiento.setOpaque(true);
        jtfFechaLanzamiento.setBackground(Color.WHITE);
        
         jtfPlataforma.setOpaque(true);
        jtfPlataforma.setBackground(Color.WHITE);
        
         jtfStock.setOpaque(true);
        jtfStock.setBackground(Color.WHITE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        RegistrarAdmin = new javax.swing.JMenuItem();
        VerHistorial = new javax.swing.JMenuItem();
        LogOut = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        Toolbar = new javax.swing.JPanel();
        btnUsuario = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        Panel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jcbClasifiacion = new javax.swing.JComboBox<>();
        jtfPrecio = new javax.swing.JTextField();
        jtfNombre = new javax.swing.JTextField();
        jtfFechaLanzamiento = new javax.swing.JTextField();
        jtfGenero = new javax.swing.JTextField();
        jtfPlataforma = new javax.swing.JTextField();
        jtfStock = new javax.swing.JTextField();

        jPopupMenu1.setToolTipText("");

        RegistrarAdmin.setText("REGISTRAR ADMIN");
        RegistrarAdmin.addActionListener(this::RegistrarAdminActionPerformed);
        jPopupMenu1.add(RegistrarAdmin);

        VerHistorial.setText("HISTORIAL");
        VerHistorial.addActionListener(this::VerHistorialActionPerformed);
        jPopupMenu1.add(VerHistorial);

        LogOut.setText("LOG OUT");
        LogOut.addActionListener(this::LogOutActionPerformed);
        jPopupMenu1.add(LogOut);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(241, 236, 224));

        Toolbar.setBackground(new java.awt.Color(35, 57, 91));

        btnUsuario.setBackground(new java.awt.Color(35, 57, 91));
        btnUsuario.setForeground(new java.awt.Color(35, 57, 91));
        btnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png"))); // NOI18N
        btnUsuario.setBorder(null);
        btnUsuario.setBorderPainted(false);
        btnUsuario.setFocusPainted(false);
        btnUsuario.setFocusTraversalPolicyProvider(true);
        btnUsuario.addActionListener(this::btnUsuarioActionPerformed);

        jLabel9.setBackground(new java.awt.Color(35, 57, 91));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 2, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(94, 117, 158));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("~ADMINISTRADOR~");

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoGris.png"))); // NOI18N

        javax.swing.GroupLayout ToolbarLayout = new javax.swing.GroupLayout(Toolbar);
        Toolbar.setLayout(ToolbarLayout);
        ToolbarLayout.setHorizontalGroup(
            ToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ToolbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(btnUsuario)
                .addGap(51, 51, 51))
        );
        ToolbarLayout.setVerticalGroup(
            ToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ToolbarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ToolbarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ToolbarLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLabel8.setBackground(new java.awt.Color(35, 57, 91));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(35, 57, 91));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("NUEVO VIDEOJUEGO");

        btnEliminar.setBackground(new java.awt.Color(200, 157, 60));
        btnEliminar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(241, 236, 224));
        btnEliminar.setText("REGRESAR");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnModificar.setBackground(new java.awt.Color(35, 57, 91));
        btnModificar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(241, 236, 224));
        btnModificar.setText("AÑADIR");
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        Panel2.setBackground(new java.awt.Color(249, 246, 241));

        jLabel10.setBackground(new java.awt.Color(35, 57, 91));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(77, 100, 141));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("NOMBRE:");

        jLabel11.setBackground(new java.awt.Color(35, 57, 91));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(77, 100, 141));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("PRECIO:");

        jLabel12.setBackground(new java.awt.Color(35, 57, 91));
        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(77, 100, 141));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("GÉNERO:");

        jLabel13.setBackground(new java.awt.Color(35, 57, 91));
        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(77, 100, 141));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("CLASIFICACIÓN:");

        jLabel14.setBackground(new java.awt.Color(35, 57, 91));
        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(77, 100, 141));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("PLATAFORMA:");

        jLabel15.setBackground(new java.awt.Color(35, 57, 91));
        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(77, 100, 141));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("FECHA LANZAMIENTO:");

        jLabel16.setBackground(new java.awt.Color(35, 57, 91));
        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(77, 100, 141));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("STOCK DISPONIBLE:");

        jcbClasifiacion.setForeground(new java.awt.Color(77, 100, 141));
        jcbClasifiacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A ", "B ", "B15", "C" }));
        jcbClasifiacion.addActionListener(this::jcbClasifiacionActionPerformed);
        jcbClasifiacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbClasifiacionKeyPressed(evt);
            }
        });

        jtfPrecio.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jtfPrecio.setForeground(new java.awt.Color(35, 57, 91));
        jtfPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfPrecioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfPrecioKeyTyped(evt);
            }
        });

        jtfNombre.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jtfNombre.setForeground(new java.awt.Color(35, 57, 91));
        jtfNombre.addActionListener(this::jtfNombreActionPerformed);
        jtfNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfNombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNombreKeyTyped(evt);
            }
        });

        jtfFechaLanzamiento.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jtfFechaLanzamiento.setForeground(new java.awt.Color(35, 57, 91));
        jtfFechaLanzamiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfFechaLanzamientoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfFechaLanzamientoKeyTyped(evt);
            }
        });

        jtfGenero.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jtfGenero.setForeground(new java.awt.Color(35, 57, 91));
        jtfGenero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfGeneroKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfGeneroKeyTyped(evt);
            }
        });

        jtfPlataforma.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jtfPlataforma.setForeground(new java.awt.Color(35, 57, 91));
        jtfPlataforma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfPlataformaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfPlataformaKeyTyped(evt);
            }
        });

        jtfStock.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jtfStock.setForeground(new java.awt.Color(35, 57, 91));
        jtfStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfStockKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfStockKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout Panel2Layout = new javax.swing.GroupLayout(Panel2);
        Panel2.setLayout(Panel2Layout);
        Panel2Layout.setHorizontalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel2Layout.createSequentialGroup()
                        .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfPrecio)
                            .addComponent(jtfNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                            .addComponent(jtfGenero, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                            .addComponent(jcbClasifiacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Panel2Layout.createSequentialGroup()
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jtfStock))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Panel2Layout.createSequentialGroup()
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfPlataforma, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Panel2Layout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addGap(18, 18, 18)
                            .addComponent(jtfFechaLanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(774, Short.MAX_VALUE))
        );
        Panel2Layout.setVerticalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jtfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jcbClasifiacion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jtfGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jtfFechaLanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jtfPlataforma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jtfStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(119, 119, 119)
                            .addComponent(Panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(595, 595, 595)
                            .addComponent(jLabel8))))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(157, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
        jPopupMenu1.show(btnUsuario, 0, btnUsuario.getHeight());
    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void RegistrarAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarAdminActionPerformed
        frmRegistroAdministrador ventana = new frmRegistroAdministrador();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegistrarAdminActionPerformed

    private void VerHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerHistorialActionPerformed
        frmHistorial ventana = new frmHistorial();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VerHistorialActionPerformed

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        frmLogin ventana = new frmLogin();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogOutActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (jtfNombre.getText().trim().isEmpty()
                || jtfPrecio.getText().trim().isEmpty()
                || jtfGenero.getText().trim().isEmpty()
                || jtfFechaLanzamiento.getText().trim().isEmpty()
                || jtfPlataforma.getText().trim().isEmpty()
                || jtfStock.getText().trim().isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Por favor, llene todos los campos antes de añadir el videojuego.",
                    "Campos Vacios",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            String nombre = jtfNombre.getText().trim();
            double precio = Double.parseDouble(jtfPrecio.getText().trim().replace(",", "."));
            String genero = jtfGenero.getText().trim();
            String fechaLanzamiento = jtfFechaLanzamiento.getText().trim();
            String plataforma = jtfPlataforma.getText().trim();
            int stock = Integer.parseInt(jtfStock.getText().trim());
            String clasificacion = jcbClasifiacion.getSelectedItem().toString();

            Videojuego v = new Videojuego(model.catalogo.contadorId,clasificacion,genero,fechaLanzamiento,plataforma,model.catalogo.contadorId,nombre,precio,stock,"Videojuego");

            model.catalogo.videojuegos.encolar(v);
            model.catalogo.contadorId++;

            javax.swing.JOptionPane.showMessageDialog(this,
                    "se agrego correctamente\n",
                    "Agregar",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);

            jtfNombre.setText("");
            jtfPrecio.setText("");
            jtfGenero.setText("");
            jtfFechaLanzamiento.setText("");
            jtfPlataforma.setText("");
            jtfStock.setText("");
            jcbClasifiacion.setSelectedIndex(0);

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Precio y Stock deben ser numeros validos",
                    "Error de formato",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        frmPrincipalAdmin ventana = new frmPrincipalAdmin();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jcbClasifiacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbClasifiacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbClasifiacionActionPerformed

    private void jtfNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNombreKeyTyped

    }//GEN-LAST:event_jtfNombreKeyTyped

    private void jtfGeneroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfGeneroKeyTyped

        char c = evt.getKeyChar();
        if (!Character.isLetter(c) && c != ' '
                && c != java.awt.event.KeyEvent.VK_BACK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfGeneroKeyTyped

    private void jtfNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNombreKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            jtfPrecio.requestFocus();
        }
    }//GEN-LAST:event_jtfNombreKeyPressed

    private void jtfGeneroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfGeneroKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            jtfFechaLanzamiento.requestFocus();
        }
    }//GEN-LAST:event_jtfGeneroKeyPressed

    private void jtfPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPrecioKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != '.'
                && c != java.awt.event.KeyEvent.VK_BACK_SPACE) {
            evt.consume();
        }
        if (c == '.' && jtfPrecio.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfPrecioKeyTyped

    private void jtfPrecioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPrecioKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            jcbClasifiacion.requestFocus();
        }
    }//GEN-LAST:event_jtfPrecioKeyPressed

    private void jcbClasifiacionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbClasifiacionKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            jtfGenero.requestFocus();
        }
    }//GEN-LAST:event_jcbClasifiacionKeyPressed

    private void jtfFechaLanzamientoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfFechaLanzamientoKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            jtfPlataforma.requestFocus();
        }
    }//GEN-LAST:event_jtfFechaLanzamientoKeyPressed

    private void jtfStockKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfStockKeyPressed
        
    }//GEN-LAST:event_jtfStockKeyPressed

    private void jtfFechaLanzamientoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfFechaLanzamientoKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != '/'
                && c != java.awt.event.KeyEvent.VK_BACK_SPACE) {
            evt.consume();
        }
        if (jtfFechaLanzamiento.getText().length() >= 10
                && c != java.awt.event.KeyEvent.VK_BACK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfFechaLanzamientoKeyTyped

    private void jtfPlataformaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPlataformaKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isLetter(c) && c != ' ' && c != '-'
                && c != java.awt.event.KeyEvent.VK_BACK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfPlataformaKeyTyped

    private void jtfPlataformaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPlataformaKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            jtfStock.requestFocus();
        }
    }//GEN-LAST:event_jtfPlataformaKeyPressed

    private void jtfStockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfStockKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)
                && c != java.awt.event.KeyEvent.VK_BACK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfStockKeyTyped

    private void jtfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmNuevoVideojuego().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem LogOut;
    private javax.swing.JPanel Panel2;
    private javax.swing.JMenuItem RegistrarAdmin;
    private javax.swing.JPanel Toolbar;
    private javax.swing.JMenuItem VerHistorial;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JComboBox<String> jcbClasifiacion;
    private javax.swing.JTextField jtfFechaLanzamiento;
    private javax.swing.JTextField jtfGenero;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfPlataforma;
    private javax.swing.JTextField jtfPrecio;
    private javax.swing.JTextField jtfStock;
    private javax.swing.JLabel lblLogo;
    // End of variables declaration//GEN-END:variables
}
