/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;
import javax.swing.table.JTableHeader;

/**
 *
 * @author shari
 */
public class frmPrincipalAdmin extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmPrincipalAdmin.class.getName());

    /**
     * Creates new form frmPrincipalAdmin
     */
    public frmPrincipalAdmin() {
        initComponents();
        this.setExtendedState(frmPrincipalAdmin.MAXIMIZED_BOTH);

        ImageIcon icono = new ImageIcon(
                getClass().getResource("/imagenes/usuario.png")
        );

        Image img = icono.getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH);
        btnUsuario.setIcon(new ImageIcon(img));

        ImageIcon logo = new ImageIcon(getClass().getResource("/imagenes/logoGris.png"));
        Image imagenEscalada = logo.getImage().getScaledInstance(lblLogo.getWidth(), lblLogo.getHeight(), Image.SCALE_SMOOTH);
        lblLogo.setIcon(new ImageIcon(imagenEscalada));

        btnAgregarConsola.setHorizontalTextPosition(SwingConstants.CENTER);
        btnAgregarConsola.setVerticalTextPosition(SwingConstants.BOTTOM);

        btnAgregarVideojuego.setHorizontalTextPosition(SwingConstants.CENTER);
        btnAgregarVideojuego.setVerticalTextPosition(SwingConstants.BOTTOM);

        TablaProductos.setGridColor(new Color(174, 172, 160));
        TablaProductos.setRowHeight(40);
        TablaProductos.setShowGrid(true);

        JTableHeader header = TablaProductos.getTableHeader();

        header.setBackground(new Color(174, 172, 160));
        header.setForeground(Color.BLACK);
        header.setFont(new Font("Times New Roman", Font.BOLD, 14));
        header.setPreferredSize(new Dimension(header.getWidth(), 35));
        

        TablaProductos.setFont(new Font("Times New Roman", Font.PLAIN, 14));
        TablaProductos.setBackground(new Color(241, 236, 224));
        TablaProductos.setSelectionBackground(new Color(77, 100, 141));
        TablaProductos.setSelectionForeground(Color.WHITE);
        
        TablaProductos.getTableHeader().setReorderingAllowed(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        RegistrarAdmin = new javax.swing.JMenuItem();
        VerHistorial = new javax.swing.JMenuItem();
        LogOut = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        Toolbar = new javax.swing.JPanel();
        btnUsuario = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnAgregarConsola = new javax.swing.JButton();
        btnAgregarVideojuego = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProductos = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();

        jPopupMenu1.setToolTipText("");

        RegistrarAdmin.setText("REGISTRAR ADMIN");
        RegistrarAdmin.addActionListener(this::RegistrarAdminActionPerformed);
        jPopupMenu1.add(RegistrarAdmin);

        VerHistorial.setText("HISTORIAL");
        VerHistorial.addActionListener(this::VerHistorialActionPerformed);
        jPopupMenu1.add(VerHistorial);

        LogOut.setText("LOG OUT");
        LogOut.addActionListener(this::LogOutActionPerformed);
        jPopupMenu1.add(LogOut);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(241, 236, 224));

        Toolbar.setBackground(new java.awt.Color(35, 57, 91));

        btnUsuario.setBackground(new java.awt.Color(35, 57, 91));
        btnUsuario.setForeground(new java.awt.Color(35, 57, 91));
        btnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png"))); // NOI18N
        btnUsuario.setBorder(null);
        btnUsuario.setBorderPainted(false);
        btnUsuario.setComponentPopupMenu(jPopupMenu1);
        btnUsuario.setFocusPainted(false);
        btnUsuario.setFocusTraversalPolicyProvider(true);
        btnUsuario.addActionListener(this::btnUsuarioActionPerformed);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoGris.png"))); // NOI18N

        jLabel9.setBackground(new java.awt.Color(35, 57, 91));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 2, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(94, 117, 158));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("~ADMINISTRADOR~");

        javax.swing.GroupLayout ToolbarLayout = new javax.swing.GroupLayout(Toolbar);
        Toolbar.setLayout(ToolbarLayout);
        ToolbarLayout.setHorizontalGroup(
            ToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ToolbarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(btnUsuario)
                .addGap(30, 30, 30))
        );
        ToolbarLayout.setVerticalGroup(
            ToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ToolbarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addGroup(ToolbarLayout.createSequentialGroup()
                        .addGroup(ToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ToolbarLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel9)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        btnAgregarConsola.setBackground(new java.awt.Color(5, 18, 35));
        btnAgregarConsola.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAgregarConsola.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarConsola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mas.png"))); // NOI18N
        btnAgregarConsola.setText("Agregar Consola");
        btnAgregarConsola.addActionListener(this::btnAgregarConsolaActionPerformed);

        btnAgregarVideojuego.setBackground(new java.awt.Color(5, 18, 35));
        btnAgregarVideojuego.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAgregarVideojuego.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarVideojuego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mas.png"))); // NOI18N
        btnAgregarVideojuego.setText("Agregar Videojuego");
        btnAgregarVideojuego.setIconTextGap(5);
        btnAgregarVideojuego.addActionListener(this::btnAgregarVideojuegoActionPerformed);

        TablaProductos.setBackground(new java.awt.Color(241, 236, 224));
        TablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "FECHA", "PRODUCTO", "TIPO", "STOCK"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaProductos);

        jLabel8.setBackground(new java.awt.Color(35, 57, 91));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(35, 57, 91));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("PRODUCTOS");

        btnEliminar.setBackground(new java.awt.Color(200, 157, 60));
        btnEliminar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(241, 236, 224));
        btnEliminar.setText("ELIMINAR");

        btnModificar.setBackground(new java.awt.Color(200, 157, 60));
        btnModificar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(241, 236, 224));
        btnModificar.setText("MODIFICAR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(454, 454, 454)
                                .addComponent(btnAgregarConsola, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(btnAgregarVideojuego, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(657, 657, 657)
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 173, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(192, 192, 192)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(494, 494, 494))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAgregarConsola, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(btnAgregarVideojuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
        jPopupMenu1.show(btnUsuario, 0, btnUsuario.getHeight());
    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void btnAgregarConsolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarConsolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarConsolaActionPerformed

    private void btnAgregarVideojuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarVideojuegoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarVideojuegoActionPerformed

    private void RegistrarAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarAdminActionPerformed
        frmRegistroAdministrador ventana = new frmRegistroAdministrador();
        ventana.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_RegistrarAdminActionPerformed

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        frmLogin ventana = new frmLogin();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogOutActionPerformed

    private void VerHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerHistorialActionPerformed
        frmHistorial ventana = new frmHistorial();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VerHistorialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmPrincipalAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem LogOut;
    private javax.swing.JMenuItem RegistrarAdmin;
    private javax.swing.JTable TablaProductos;
    private javax.swing.JPanel Toolbar;
    private javax.swing.JMenuItem VerHistorial;
    private javax.swing.JButton btnAgregarConsola;
    private javax.swing.JButton btnAgregarVideojuego;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblLogo;
    // End of variables declaration//GEN-END:variables
}
