/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.RegistroAdminController;
import controller.RegistroUsrController;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author shari
 */
public class frmRegistroAdministrador extends javax.swing.JFrame {

    private RegistroAdminController controlador;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmRegistroAdministrador.class.getName());

    /**
     * Creates new form frmRegistroAdministrador
     */
    public frmRegistroAdministrador() {
        initComponents();

        controlador = new RegistroAdminController(this);

        ImageIcon logo = new ImageIcon(getClass().getResource("/imagenes/iconoPOE.png"));
        Image imagenEscalada = logo.getImage().getScaledInstance(lblLogo.getWidth(), lblLogo.getHeight(), Image.SCALE_SMOOTH);
        lblLogo.setIcon(new ImageIcon(imagenEscalada));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jtfContraseña = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jtfCorreo = new javax.swing.JTextField();
        jcbTurno = new javax.swing.JComboBox<>();
        btnRegistrarse = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jtfSalario = new javax.swing.JTextField();
        Regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel9.setBackground(new java.awt.Color(35, 57, 91));
        jPanel9.setPreferredSize(new java.awt.Dimension(1272, 678));

        jPanel10.setBackground(new java.awt.Color(241, 236, 224));

        jLabel8.setBackground(new java.awt.Color(35, 57, 91));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(77, 100, 141));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("JUEGA.   EXPLORA.   COMPRA.");

        jLabel9.setBackground(new java.awt.Color(35, 57, 91));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(35, 57, 91));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("¡BIENVENIDO!");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(135, 135, 135))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel8)
                .addGap(236, 236, 236))
        );

        jLabel10.setBackground(new java.awt.Color(77, 100, 141));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(241, 236, 224));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("SIGN UP");

        jtfNombre.setBackground(new java.awt.Color(35, 57, 91));
        jtfNombre.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jtfNombre.setForeground(new java.awt.Color(77, 100, 141));
        jtfNombre.setText("NOMBRE");
        jtfNombre.setBorder(null);
        jtfNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfNombreFocusLost(evt);
            }
        });
        jtfNombre.addActionListener(this::jtfNombreActionPerformed);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jtfContraseña.setBackground(new java.awt.Color(35, 57, 91));
        jtfContraseña.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jtfContraseña.setForeground(new java.awt.Color(77, 100, 141));
        jtfContraseña.setText("CONTRASEÑA");
        jtfContraseña.setBorder(null);
        jtfContraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfContraseñaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfContraseñaFocusLost(evt);
            }
        });
        jtfContraseña.addActionListener(this::jtfContraseñaActionPerformed);

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        jtfCorreo.setBackground(new java.awt.Color(35, 57, 91));
        jtfCorreo.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jtfCorreo.setForeground(new java.awt.Color(77, 100, 141));
        jtfCorreo.setText("CORREO ELECTRÓNICO");
        jtfCorreo.setBorder(null);
        jtfCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfCorreoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfCorreoFocusLost(evt);
            }
        });
        jtfCorreo.addActionListener(this::jtfCorreoActionPerformed);

        jcbTurno.setBackground(new java.awt.Color(183, 182, 181));
        jcbTurno.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jcbTurno.setForeground(new java.awt.Color(35, 57, 91));
        jcbTurno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TURNO", "Matutino", "Vespertino" }));

        btnRegistrarse.setBackground(new java.awt.Color(241, 236, 224));
        btnRegistrarse.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnRegistrarse.setForeground(new java.awt.Color(35, 57, 91));
        btnRegistrarse.setText("REGISTRARSE");
        btnRegistrarse.addActionListener(this::btnRegistrarseActionPerformed);

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));

        jtfSalario.setBackground(new java.awt.Color(35, 57, 91));
        jtfSalario.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jtfSalario.setForeground(new java.awt.Color(77, 100, 141));
        jtfSalario.setText("SALARIO");
        jtfSalario.setBorder(null);
        jtfSalario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfSalarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfSalarioFocusLost(evt);
            }
        });
        jtfSalario.addActionListener(this::jtfSalarioActionPerformed);

        Regresar.setBackground(new java.awt.Color(177, 184, 196));
        Regresar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Regresar.setForeground(new java.awt.Color(35, 57, 91));
        Regresar.setText("Regresar");
        Regresar.addActionListener(this::RegresarActionPerformed);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                            .addComponent(jtfNombre)
                            .addComponent(jSeparator1)
                            .addComponent(jtfContraseña)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator3)
                            .addComponent(jtfCorreo)
                            .addComponent(jcbTurno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfSalario)
                            .addComponent(jSeparator4))
                        .addGap(0, 114, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addComponent(Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addComponent(btnRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(215, 215, 215))))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel10)
                .addGap(34, 34, 34)
                .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtfContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jtfSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jcbTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(btnRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addComponent(Regresar)
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 1285, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfNombreFocusGained
        if (jtfNombre.getText().equals("NOMBRE")) {
            jtfNombre.setText("");
            jtfNombre.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_jtfNombreFocusGained

    private void jtfNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfNombreFocusLost
        if (jtfNombre.getText().isEmpty()) {
            jtfNombre.setText("NOMBRE");
            jtfNombre.setForeground(new Color(77, 100, 141));
        }
    }//GEN-LAST:event_jtfNombreFocusLost

    private void jtfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNombreActionPerformed

    private void jtfContraseñaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfContraseñaFocusGained
        if (jtfContraseña.getText().equals("CONTRASEÑA")) {
            jtfContraseña.setText("");
            jtfContraseña.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_jtfContraseñaFocusGained

    private void jtfContraseñaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfContraseñaFocusLost
        if (jtfContraseña.getText().isEmpty()) {
            jtfContraseña.setText("CONTRASEÑA");
            jtfContraseña.setForeground(new Color(77, 100, 141));
        }
    }//GEN-LAST:event_jtfContraseñaFocusLost

    private void jtfContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfContraseñaActionPerformed

    private void jtfCorreoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCorreoFocusGained
        if (jtfCorreo.getText().equals("CORREO ELECTRÓNICO")) {
            jtfCorreo.setText("");
            jtfCorreo.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_jtfCorreoFocusGained

    private void jtfCorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCorreoFocusLost
        if (jtfCorreo.getText().isEmpty()) {
            jtfCorreo.setText("CORREO ELECTRÓNICO");
            jtfCorreo.setForeground(new Color(77, 100, 141));
        }
    }//GEN-LAST:event_jtfCorreoFocusLost

    private void jtfCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCorreoActionPerformed

    private void jtfSalarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfSalarioFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfSalarioFocusGained

    private void jtfSalarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfSalarioFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfSalarioFocusLost

    private void jtfSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfSalarioActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        frmPrincipalAdmin ventana = new frmPrincipalAdmin();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegresarActionPerformed

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
        controlador.registrar();
    }//GEN-LAST:event_btnRegistrarseActionPerformed

    public javax.swing.JTextField getJtfNombre() {
        return jtfNombre;
    }

    public javax.swing.JTextField getJtfCorreo() {
        return jtfCorreo;
    }

    public javax.swing.JTextField getJtfContraseña() {
        return jtfContraseña;
    }

    public javax.swing.JTextField getJtfSalario() {
        return jtfSalario;
    }

    public javax.swing.JComboBox<String> getJcbTurno() {
        return jcbTurno;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmRegistroAdministrador().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Regresar;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JComboBox<String> jcbTurno;
    private javax.swing.JTextField jtfContraseña;
    private javax.swing.JTextField jtfCorreo;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfSalario;
    private javax.swing.JLabel lblLogo;
    // End of variables declaration//GEN-END:variables
}
